<a href="https://colab.research.google.com/github/AzulBarr/Aprendizaje-Automatico/blob/main/notebooks/notebook_01_herramientas-published.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/aprendizaje-automatico-dc-uba-ar/material/blob/main/notebooks/notebook_01_herramientas-published.ipynb)

# Introducción a las herramientas
### Bienvenidos a Jupyter Notebooks!

En este notebook exploraremos algunas de las funcionalidades básicas de bibliotecas en python3 que utilizaremos durante todo el cuatrimestre.

Consejos:
- Chequear "Help / Keyboard shortcuts"
- Asumimos conocimiento de python3, en caso de no tenerlo, se puede empezar con: https://learnxinyminutes.com/docs/python3/
- Consultar: https://jakevdp.github.io/PythonDataScienceHandbook/ como introducción a los paquetes pandas, numpy y matplotlib
- Para ejecutar las notebooks de la materia hay 2 alternativas:
  - instalar python3 y jupyter en la computadora local
  - utilizar GoogleColab
  
Esta práctica no es exhaustiva y está pensada para tener una primera aproximación sobre la cual explorar funcionalidades. Se recomienda fuertemente explorar las referencias propuestas.


## Carga de modulos

In [1]:
%matplotlib inline

import numpy as np # NUMPY
import pandas as pd # PANDAS
import matplotlib.pyplot as plt # MATPLOTLIB
import seaborn as sns # SEABORN
import scipy
import sklearn


#### Si la celda anterior no corre bien, chequear que se hayan instalado las librerías. En la terminal correr:

```bash
$ pip3 install numpy pandas matplotlib seaborn scipy sklearn
```

## Listas

In [2]:
lista_python = [1,2,3,4]
lista_python

[1, 2, 3, 4]

In [8]:
# Descomentar y probar lo siguiente:

# print(lista_python + lista_python)  # funciona? SI
# print(lista_python * 2)  # funciona? SI
# print(lista_python ** 3) # funciona? NO
# print(lista_python - lista_python)  # funciona? NO
# print(lista_python * lista_python)  # funciona? NO


## Numpy

In [9]:
array_numpy = np.array([1,2,3,4,5])
array_numpy

array([1, 2, 3, 4, 5])

In [10]:
print(array_numpy + array_numpy)
print(array_numpy * 2)
print(array_numpy ** 3)
print(array_numpy * array_numpy)
print(array_numpy - array_numpy)


[ 2  4  6  8 10]
[ 2  4  6  8 10]
[  1   8  27  64 125]
[ 1  4  9 16 25]
[0 0 0 0 0]


#### Arreglos multidimensionales (Vectores, Matrices, Tensores, etc)

In [11]:
v = np.array([1,2,3,4,5,6])
print("Un vector de dim: ", v.shape)

m = np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
print("Una matriz de dim:", m.shape)

t = np.array([[[1,2,3], [2,3,3]], [[1,3,2], [4,3,2]],
              [[4,2,3], [0,3,-1]], [[10,3,21], [34,13,12]]])
print("Un tensor de dim: ", t.shape) # Vector de matrices, o matriz de vectores

Un vector de dim:  (6,)
Una matriz de dim: (4, 3)
Un tensor de dim:  (4, 2, 3)


In [12]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
print("suma con la función sum:", sum(m))
print("función sum de numpy array.sum:", m.sum()) # suma toda la matriz
print("función sum de numpy np.sum:", np.sum(m)) # suma toda la matriz

suma con la función sum: [22 26 30]
función sum de numpy array.sum: 78
función sum de numpy np.sum: 78


- ```sum(m)``` devuelve la suma de cada columna, ¿por qué?

### Ejercicios:

Para la siguiente serie de ejercicios explorar las funciones del módulo `NumPy`:
`sum; vstack; hstack; shape; reshape; linspace; dot`

Para acceder a la documentación se puede ejecutar en una celda el nombre de la función seguido de un signo de pregunta (?).

Ej:```np.vstack?```


Implementar las siguientes funciones:

In [38]:
np.vstack?

In [50]:
def sumar_por_fila(mat: np.ndarray) -> np.ndarray:
    # que devuelve la suma de cada fila de la matriz m.
    # Debe devolver un vector columna: (n x 1)
    n, m = np.shape(mat)
    res = np.sum(mat, axis=1)
    res = np.reshape(res, (n, 1))
    return res

def transponer(mat: np.ndarray) -> np.ndarray:
    # que transponga la matriz m.
    return np.transpose(mat)

def agregar_fila(mat: np.ndarray, row: np.ndarray) -> np.ndarray:
    # que agregue la fila row a la matriz m.
    return np.vstack((mat, row))

def convertir_a_columna(x: np.ndarray) -> np.ndarray:
    # que convierta un vector fila en un vector columna. Es decir, de (1 x n) a (n x 1).
    return np.reshape(x, (len(x), 1))

def agregar_columna(mat: np.ndarray, col: np.ndarray) -> np.ndarray:
    # que agregue la columna col a la matriz m.
    return np.hstack((mat, col))

def producto(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    # que multiplique los vectores x e y (producto interno): x^t.y
    return np.dot(x, y)

def equiespaciados(n: int, a: float, b: float) -> np.ndarray:
    # que devuelva n puntos equiespaciados entre a y b.
    return np.linspace(a, b, n)




In [52]:
print(f"M = \n {m}")

print(f"Suma por fila\n{sumar_por_fila(m)}")

print(f"Transpuesta:\n{transponer(m)}")

print(f"Fila nueva:\n{agregar_fila(m, np.array([13,14,15]))}")

fila = np.array([0,0,0,0])
columna = convertir_a_columna(fila)
print(f"fila = \n {fila}")
print(f"shape de fila: {np.shape(fila)}")
print(f"A vector columna:\n{columna}")
print(f"shape de columna: {np.shape(columna)}")

print(f"Columna nueva:\n{agregar_columna(m, columna)}")

x = np.array([0,3,2,0])
y =  np.array([4,1,2,2])
print(f"producto: {producto(x,y)}")

print(f"equiespaciados: \n{equiespaciados(3, 10, 4)}")

M = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Suma por fila
[[ 6]
 [15]
 [24]
 [33]]
Transpuesta:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Fila nueva:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
fila = 
 [0 0 0 0]
shape de fila: (4,)
A vector columna:
[[0]
 [0]
 [0]
 [0]]
shape de columna: (4, 1)
Columna nueva:
[[ 1  2  3  0]
 [ 4  5  6  0]
 [ 7  8  9  0]
 [10 11 12  0]]
producto: 7
equiespaciados: 
[10.  7.  4.]


## Matplotlib

Matplotlib es la biblioteca más utilizada en python para generar gráficos.

[Tutorial oficial](https://matplotlib.org/stable/tutorials/introductory/pyplot.html).

Se pueden ver ejemplos (con el código para generar gráficos) en una [galería de gráficos](https://matplotlib.org/stable/gallery/index.html), explorar gráficos puede dar ideas sobre posibles formas de ver datos propios.

Sobre matplotlib se han generado nuevas bibliotecas como [seaborn](https://seaborn.pydata.org/) que interactua bien con pandas. [Tutorial](https://seaborn.pydata.org/tutorial.html) y [Galería de ejemplos](https://seaborn.pydata.org/examples/index.html).

In [ ]:
with plt.xkcd():
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    ax.spines['right'].set_color('none')
    ax.spines['top'].set_color('none')
    plt.xticks([])
    plt.yticks([])
    ax.set_ylim([-30, 10])

    data = np.ones(100)
    data[70:] -= np.arange(30)

    plt.annotate(
        'INICIO DEL MUNDIAL',
        xy=(70, 1), arrowprops=dict(arrowstyle='->'), xytext=(15, -10))

    plt.plot(data)

    plt.xlabel('DIAS')
    plt.ylabel('PRODUCTIVIDIDAD');
plt.rcdefaults()

In [ ]:
x = np.linspace(-5, 5, 15)
print("X=", x)

y = np.sin(x) # aplica sen a cada elemento.
print("Y=", y)



In [ ]:
# Descomentar lo siguiente para probar:
# plt.plot?

plt.figure(figsize=(10, 1.5))
plt.plot(x, y, ".-")

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(15, 3))
axes[0].plot(x, y, marker="x", color="red", linewidth=1)

axes[1].plot(x, y, marker="x", color="blue", linewidth=0.5)
axes[1].plot(x, y+1, marker="x", linewidth=0.4)

axes[2].plot(y, x, ".-");


In [ ]:
# Descomentar lo siguiente y probar
# plt.scatter?

In [ ]:
plt.figure(figsize=(10, 3))
x1 = np.arange(0, 100)
x2 = np.random.rand(100) * 5
x3 = np.random.rand(100) - 1
sizes = np.random.rand(100) * 100
plt.scatter(x1, x2, color="blue", marker="x", s=sizes) # tamaños al azar
plt.scatter(x1, x3, color="red", s=np.linspace(0, 300, 100), alpha=0.5) # tamaños crecientes


### Ejercicios

Completar los siguientes items:

1. Escribir una función $f(n, a, b)$ con $n, a, b$ naturales que devuelva $n$ números reales aleatorios en el intervalo $[a, b]$;
1. Escribir una función $g(n, m, v)$  que devuelva $n$ números reales aleatorios muestreando una distribución normal con media $m$ y varianza $v$.
1. Plotear luego histogramas para $f(1000, 10, 20)$ y $g(1000, 3, 9)$.
1. Para los datos recién generados con la función $g$, estimar los parámetros muestrales y graficar junto al histograma, la densidad de una normal con los parámetros estimados.

In [ ]:
def f(n: int, a: int, b: int) -> np.ndarray:
    return "<<completar>>"


def g(n: int, m: float, v: float) -> np.ndarray:
    return "<<completar>>"


## Pandas

In [ ]:
import pandas as pd
from IPython.display import display

# Creamos un dataset
data = {"Nombre": ["El Profesor", "Mónica Gaztambide", "Raquel Murillo", "Tokio","Berlín","Alison Parker"],
        "Rol" : ["Atracador", "Rehén", "Policia", "Atracador", "Atracador", "Rehén"],
        "Edad": [40, 35, 38, 25, 44, 16]
       }

df = pd.DataFrame(data)
df

Explorar el data set con los comandos: `.head(3), .tail(2), .describe(), .T`.

¿Qué información nos muestra cada comando?

Ordenar los datos por Rol (alfabético inverso) y luego por edad (ascendente).

In [ ]:
display(df[df.Edad > 30])
display(df.groupby("Rol").mean())

In [ ]:
mascara_edad = (df.Edad > 30)
mascara_rol = (df.Rol == "Atracador")
mascara = mascara_edad & mascara_rol
print("Máscara: \n", mascara, sep="")
df[mascara]

Repasar la página [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) para una completar la primera aproximación a pandas.